// Copies the skill dictionary from the website (client/src/lib/skills.ts) into the server,
// so job ads are matched against exactly the same skills students pick from.
// Run after changing the dictionary: npm run sync-skills
import { readFileSync, writeFileSync } from 'node:fs'
const src = readFileSync(new URL('../../client/src/lib/skills.ts', import.meta.url), 'utf8')
const start = src.indexOf('const GROUPS')
// Works with both Unix and Windows line endings
const close = /\r?\n}\r?\n/g
close.lastIndex = start
const m = close.exec(src)
if (start < 0 || !m) throw new Error('Could not find the GROUPS dictionary in client/src/lib/skills.ts')
const end = m.index + m[0].length
const header = '// GENERATED by server/scripts/sync-skills.mjs from client/src/lib/skills.ts. Do not edit by hand.\n\nexport '
writeFileSync(new URL('../src/skillsData.ts', import.meta.url), header + src.slice(start, end))
console.log('skillsData.ts updated')
